package com.weatherappde.utils.constants

object Strings {
    const val CLEAR_SKY = "Clear sky"
    const val MAINLY_CLEAR = "Mainly clear"
    const val PARTLY_CLOUDY = "Partly cloudy"
    const val OVERCAST = "Overcast"
    const val FOGGY = "Foggy"
    const val DEPOSITING_RIME_FOG = "Depositing rime fog"
    const val LIGHT_DRIZZLE = "Light drizzle"
    const val MODERATE_DRIZZLE = "Moderate drizzle"
    const val DENSE_DRIZZLE = "Dense drizzle"
    const val LIGHT_FREEZING_DRIZZLE = "Slight freezing drizzle"
    const val DENSE_FREEZING_DRIZZLE = "Dense freezing drizzle"
    const val SLIGHT_RAIN = "Slight rain"
    const val MODERATE_RAIN = "Rainy"
    const val HEAVY_RAIN = "Heavy rain"
    const val HEAVY_FREEZING_RAIN = "Heavy freezing rain"
    const val SLIGHT_SNOW_FALL = "Slight snow fall"
    const val MODERATE_SNOW_FALL = "Moderate snow fall"
    const val HEAVY_SNOW_FALL = "Heavy snow fall"
    const val SNOW_GRAINS = "Snow grains"
    const val SLIGHT_RAIN_SHOWERS = "Slight rain showers"
    const val MODERATE_RAIN_SHOWERS = "Moderate rain showers"
    const val VIOLENT_RAIN_SHOWERS = "Violent rain showers"
    const val SLIGHT_SNOW_SHOWERS = "Light snow showers"
    const val HEAVY_SNOW_SHOWERS = "Heavy snow showers"
    const val MODERATE_THUNDERSTORM = "Moderate thunderstorm"
    const val SLIGHT_HAIL_THUNDERSTORM = "Thunderstorm with slight hail"
    const val HEAVY_HAIL_THUNDERSTORM = "Thunderstorm with heavy hail"
    const val WEATHER_ENDPOINT = "v1/forecast?hourly=temperature_2m,weathercode,relativehumidity_2m,windspeed_10m,pressure_msl"
    const val UNKNOWN_ERROR = "Unknown Error"
    const val BASE_URL = "https://api.open-meteo.com/"
}